# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pkg/proto/assistant.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'pkg/proto/assistant.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x19pkg/proto/assistant.proto\x12\x0c\x61ssistant.v1\"F\n\x0b\x43hatRequest\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\"_\n\x0c\x43hatResponse\x12\x12\n\nsession_id\x18\x01 \x01(\t\x12\x15\n\rtext_response\x18\x02 \x01(\t\x12\x12\n\naudio_data\x18\x03 \x01(\x0c\x12\x10\n\x08is_final\x18\x04 \x01(\x08\x32U\n\x10\x41ssistantService\x12\x41\n\x04\x43hat\x12\x19.assistant.v1.ChatRequest\x1a\x1a.assistant.v1.ChatResponse(\x01\x30\x01\x42/Z-github.com/evisdrenova/ember-server/pkg/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pkg.proto.assistant_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z-github.com/evisdrenova/ember-server/pkg/proto'
  _globals['_CHATREQUEST']._serialized_start=43
  _globals['_CHATREQUEST']._serialized_end=113
  _globals['_CHATRESPONSE']._serialized_start=115
  _globals['_CHATRESPONSE']._serialized_end=210
  _globals['_ASSISTANTSERVICE']._serialized_start=212
  _globals['_ASSISTANTSERVICE']._serialized_end=297
# @@protoc_insertion_point(module_scope)
